### ISSUE TITLE
Storybook code snippets show MDXCreateElement instead of component code

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/react-components#291] opened 2020-09-23 14:49 UTC
Many of the code examples in the storybook show `MDXCreateElement` (which looks like some StoryBook internal).
This is not a very useful as documentation:

<img width="717" alt="Screenshot 2020-09-23 at 16 47 07" src="https://user-images.githubusercontent.com/83575/94029094-bf193280-fdbc-11ea-9105-f9d858341ca0.png">

**Comment by huwshimi** [comment] 2020-09-23 23:22
Dupe of https://github.com/canonical-web-and-design/react-components/issues/254

**Closed by huwshimi** 2020-09-23 23:22 UTC
