### ISSUE TITLE
Code examples have black text on black background making it impossible to read

### ISSUE THREAD

**Issue by steverydz** [canonical-web-and-design/react-components#480] opened 2021-06-10 10:32 UTC
e.g https://canonical-web-and-design.github.io/react-components/?path=/docs/maintable--expanding

<img width="1158" alt="Screenshot 2021-06-10 at 11 31 09" src="https://user-images.githubusercontent.com/501889/121510383-77d0e180-c9df-11eb-82ac-4658f7b15b17.png">

**Comment by bartaz** [comment] 2021-06-21 08:36
Thanks @steverydz, we are aware of the issue, but it seems to be a problem with storybook that we didn't manage to figure our yet.

Duplicate of #292

**Closed by bartaz** 2021-06-21 08:36 UTC
