### ISSUE TITLE
ActionButton doesn't support same options as Button

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/react-components#346] opened 2020-11-25 09:03 UTC
`Button` component has props to support different variants of buttons provided in Vanila (like dense, small introduced in 2.20.0, etc).

`ActionButton` uses completely seperate implementation. It doesn't use `Button` internally and requires custom classes `is-dense` to be passed to achieve same results as with props on `Button`.

For example in `SummaryButton` implemenation we need to pass classes to ActionButton, while it would be best to do it via props and not rely on devs knowing Vanilla classnames:

https://github.com/canonical-web-and-design/react-components/blob/95cf207c18125c735dcafdada9328e9cb516261a/src/components/SummaryButton/SummaryButton.tsx#L28-L34

### Expected

`ActionButton` should support same props as `Button` component. Ideally, it should use `Button`.

**Comment by huwshimi** [comment] 2020-11-25 22:02
Dupe of https://github.com/canonical-web-and-design/react-components/issues/189.

**Closed by huwshimi** 2020-11-25 22:02 UTC
